#!/bin/bash

#MYTARGET=${{matrix.target}}
MYTARGET=rockchip

source "${GITHUB_WORKSPACE}/devices/common/settings.ini"
if [ -f "${GITHUB_WORKSPACE}devices/$MYTARGET/settings.ini" ]; then
  source "${GITHUB_WORKSPACE}/devices/$MYTARGET}/settings.ini"
fi
echo "KMODS_IN_FIRMWARE=${KMODS_IN_FIRMWARE}" >> $GITHUB_ENV
echo "IPV6MOD_IN_FIRMWARE=${IPV6MOD_IN_FIRMWARE}" >> $GITHUB_ENV
echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_ENV
echo "CONFIG_FILE=${CONFIG_FILE}" >> $GITHUB_ENV
echo "DIY_SH=${DIY_SH}" >> $GITHUB_ENV
echo "FREE_UP_DISK=${FREE_UP_DISK}" >> $GITHUB_ENV
echo "UPLOAD_BIN_DIR_FOR_ARTIFACT=${UPLOAD_BIN_DIR_FOR_ARTIFACT}" >> $GITHUB_ENV
echo "UPLOAD_FIRMWARE_FOR_ARTIFACT=${UPLOAD_FIRMWARE_FOR_ARTIFACT}" >> $GITHUB_ENV
echo "UPLOAD_FIRMWARE_FOR_RELEASE=${UPLOAD_FIRMWARE_FOR_RELEASE}" >> $GITHUB_ENV
echo "UPLOAD_FIRMWARE_TO_COWTRANSFER=${UPLOAD_FIRMWARE_TO_COWTRANSFER}" >> $GITHUB_ENV
echo "UPLOAD_FIRMWARE_TO_WETRANSFER=${UPLOAD_FIRMWARE_TO_WETRANSFER}" >> $GITHUB_ENV
echo "OPENWRTROOT=${GITHUB_WORKSPACE}/openwrt" >> $GITHUB_ENV
chmod +x ${GITHUB_WORKSPACE}/scripts/*.sh
